# syntax=docker/dockerfile:1

FROM node:24.18.0-alpine AS base
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm install --global npm@12.0.1

FROM base AS dependencies
COPY package.json package-lock.json .npmrc ./
RUN npm ci

FROM base AS builder
COPY --from=dependencies /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_API_URL
ARG CABO_CLIENT_BUILD_COMMIT_ID
ARG CABO_CLIENT_BUILD_COMMIT_TIMESTAMP
ARG CABO_SERVER_BUILD_COMMIT_ID
ARG CABO_SERVER_BUILD_COMMIT_TIMESTAMP

ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV CABO_CLIENT_BUILD_COMMIT_ID=${CABO_CLIENT_BUILD_COMMIT_ID}
ENV CABO_CLIENT_BUILD_COMMIT_TIMESTAMP=${CABO_CLIENT_BUILD_COMMIT_TIMESTAMP}
ENV CABO_SERVER_BUILD_COMMIT_ID=${CABO_SERVER_BUILD_COMMIT_ID}
ENV CABO_SERVER_BUILD_COMMIT_TIMESTAMP=${CABO_SERVER_BUILD_COMMIT_TIMESTAMP}

RUN npm run lint \
    && npm run typecheck \
    && npm run build

FROM node:24.18.0-alpine AS runner
WORKDIR /app

ARG NEXT_PUBLIC_API_URL
ARG CABO_CLIENT_BUILD_COMMIT_ID
ARG CABO_CLIENT_BUILD_COMMIT_TIMESTAMP
ARG CABO_SERVER_BUILD_COMMIT_ID
ARG CABO_SERVER_BUILD_COMMIT_TIMESTAMP

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV CABO_CLIENT_BUILD_COMMIT_ID=${CABO_CLIENT_BUILD_COMMIT_ID}
ENV CABO_CLIENT_BUILD_COMMIT_TIMESTAMP=${CABO_CLIENT_BUILD_COMMIT_TIMESTAMP}
ENV CABO_SERVER_BUILD_COMMIT_ID=${CABO_SERVER_BUILD_COMMIT_ID}
ENV CABO_SERVER_BUILD_COMMIT_TIMESTAMP=${CABO_SERVER_BUILD_COMMIT_TIMESTAMP}
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs \
    && adduser --system --uid 1001 --ingroup nodejs nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
  CMD wget -qO- "http://127.0.0.1:${PORT}/" >/dev/null || exit 1

CMD ["node", "server.js"]
