export interface User {
  id: string | null;
  name: string | null;
  username: string | null;
  token: string | null;
  status: string | null;
  isPublicLog?: boolean | null;
  bio: string | null;
  creationDate: string | null;
  gamesWon: number | null;
  roundsWon: number | null;
  roundsPlayed?: number | null;
  rounds?: number | null;
  roundCount?: number | null;
  gamesPlayed?: number | null;
  games?: number | null;
  averageScorePerRound: number | null;
  overallRank: number | null;
  profileCharacterId?: string | null;
  preferredColorPriority?: string[] | null;
  menuBackgroundId?: string | null;
  gameBackgroundId?: string | null;
  primaryColorId?: string | null;
  appearanceMode?: string | null;
  tutorialsEnabled?: boolean | null;
  musicVolume?: number | null;
  soundEffectsVolume?: number | null;
  musicBlacklist?: string[] | null;
  joinableSessionId?: string | null;
}
 
